### ISSUE TITLE
Enhancement: use "patches" instead of "patchesStrategicMerge"

### ISSUE THREAD

**Issue by jfavellar90** [overhangio/tutor#941]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem, but a functionality limitation. [PatchesStrategicMerge](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/) (used [here](https://github.com/overhangio/tutor/blob/674e63a3927b5e56590887a14e60f3c49ff6b526/tutor/templates/kustomization.yml#L69) ) is going to be deprecated in future releases of the Kustomization API and can be easily replaced by the [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) key. It is more powerful and allows defining different patch types (including PatchesStrategicMerge). It works for the Kustomization API version currently used by Tutor, from Kubectl 1.24 and upwards (See the Kubectl-Kustomize version equivalence [here](https://github.com/kubernetes-sigs/kustomize#kubectl-integration) ).  

**Describe the solution you'd like**

The set of changes is pretty straightforward, please see this [commit](https://github.com/eduNEXT/tutor/commit/a8e8e7e19c19c7ec60e7a9bd4d45edd103b3b9ab) to take a closer look

**Comment by regisb** [comment]
Thanks for the bug description @jfavellar90. Transitioning from "patchesStrategicMerge" to "patches" is going to be a breaking change, so we should make that change in Quince.

**Comment by regisb** [comment]
Solved by #947. Thank you Jhony!

**Comment by jfavellar90** [comment]
@regisb Unfortunately we'll need to revert #947. An annoying [issue](https://github.com/kubernetes-sigs/kustomize/issues/5049) prevents having multiple patches in the same file. For instance, in the pod-autoscaling plugin, there are multiple patches in the [override.yml file](https://github.com/eduNEXT/tutor-contrib-pod-autoscaling/blob/main/tutorpod_autoscaling/patches/k8s-override) separated by `---`. This is not accepted by the new "patches" key, at least not before [Kustomize 5.2.1](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.1) (the issue was already fixed [here](https://github.com/kubernetes-sigs/kustomize/pull/5194) ). It would force to split the patches into different files, which is definitively not desirable. Given that the latest Kubectl version (1.28.4 at this date) is delivered with Kustomize 5.0.4, we'll need to delay this change until we get a version with the issued fixed.

**Comment by regisb** [comment]
Thanks for the detailed explanation @jfavellar90! I'll mark the issue as "blocked" until Kustomize 5.2.1 is the new default.

**Comment by visokoo** [comment]
In the meantime, is it possible to update this page [here](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/) to warn others of the issue that multi patches are still not fully supported with the `- patches` key? It took a little bit of googling to get to this issue as all the other issues mentioned that moving to:

```
- patches:
   - path: blah.yaml
```
should work for multi patches, but it does not with files that include the `---` separator.

**Comment by jfavellar90** [comment]
@regisb, I would like to revisit this topic. From version 1.31.x, `kubectl` is shipped with Kustomize 5.4.2, which already includes the fix to support multiple patches in the same file properly (prior kubectl versions include Kustomize < 5.2.1, which does not support single-file multiple patches).

According to the Kubernetes [eol](https://endoflife.date/kubernetes), 1.30 version drops maintenance support on 28 June. My proposal would be:
- Add a deprecation note in the Teak release informing about the changes to the "patches" key on the next release (Ulmo)
- Move definitively to "patches" key by Ulmo release.

The reasoning behind my proposal is that I'm assuming that there are still installations that run on Kubernetes versions before 1.31, so they rely on Kustomization versions < 5.2.1. This period till migrating to "patches" keys gives time to operators to be prepared. Another option is to provide a compatibility option so the patches are applied using "patchesStrategicMerge" and "patches" (I don't like this option very much). 

Let me know if you have a different position on this issue. cc @DawoudSheraz

**Comment by regisb** [comment]
I'm deferring the decision to @DawoudSheraz and @ahmed-arb.

**Comment by jfavellar90** [comment]
Hi, I'm here again, trying to push this change forward. @ahmed-arb @DawoudSheraz the migration path would be similar to the one I exposed in my previous [comment](https://github.com/overhangio/tutor/issues/941#issuecomment-2779644481). What do you think about it? Do you consider it feasible for the Ulmo release? I can work in a PR against the `ulmo` branch

**Comment by ahmed-arb** [comment]
@jfavellar90 Thanks for following up on this! I’ll move this issue from **blocked** to **in-progress**.
Please go ahead and open the PR against the `ulmo` branch.
